ServerStatusPort = 1207
ListeningAddress = "0.0.0.0"
BufferSize = 4000
PerfReportIntervalSec = 30

[[EchoingServers]]
  Label = "WORLD"
  Port = 1215

[[EchoingServers]]
  Label = "WORLD_OLD"
  Port = 1255
