ServerStatusPort = 1207
ListeningAddress = "0.0.0.0"
BufferSize = 4000

# Performance and logging options.
PerfReportIntervalSec = 30
EnablePerformanceMonitoring = true
VerboseLogging = true

[[EchoingServers]]
  Label = "WORLD"
  Port = 1215

[[EchoingServers]]
  Label = "WORLD_OLD"
  Port = 1255
