ListeningAddress = "0.0.0.0"
DefaultBufferSize = 4000

[[Servers]]
  Label = "WORLD"
  Port = 1215
  Enabled = true
  Type = "Echoing"
  BufferSize = 0

[[Servers]]
  Label = "WORLD_OLD"
  Port = 1255
  Enabled = true
  Type = "Echoing"
  BufferSize = 0

[[Servers]]
  Label = "STATUS"
  Port = 1207
  Enabled = true
  Type = "Status"
  BufferSize = 0
